version: "3.7"

networks:
  app-tier:
    driver: bridge

services:

  zookeeper:
      image: bitnami/zookeeper:${ZOOKEEPER_VERSION}
      networks:
        - app-tier
      container_name: zookeeper
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
        ALLOW_ANONYMOUS_LOGIN: yes
      ports:
        - 22181:2181
      volumes:
        - zookeeper_data:/bitnami

  kafka:
    image: kafka_with_prom_exporter:${KAFKA_VRESION}
    networks:
        - app-tier
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9094:9094
      - 7075:7075
    volumes:
      - kafka_data:/bitnami
    environment:
      KAFKA_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_ENABLE_KRAFT: no
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_JMX_HOSTNAME: kafka
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      METRICS_JMX_ENABLED: true
      KAFKA_OPTS: -javaagent:/usr/app/jmx_prometheus_javaagent-0.17.2.jar=7075:/usr/app/prom-jmx-agent-config.yml

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:${KAFKA_UI_VERSION}
    networks:
        - app-tier
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first_connect
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://connect:8083
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
    volumes:
      - kafka_ui_data:/etc/kafkaui
    depends_on:
      - kafka
      - connect

  postgres:
    image: debezium/postgres:${POSTGRES_VERSION}
    container_name: postgres
    hostname: postgres
    networks:
      - app-tier
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    
  connect:
    image: confluent_kafka_connect_with_debezium:${KAFKA_CONNECT_VERSION}
    container_name: connect
    networks:
      - app-tier
    ports:
      - 8083:8083
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: kafka-connect
      CONNECT_CONFIG_STORAGE_TOPIC: _connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: _connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
      - postgres
      - kafka
      - schema-registry
    

  schema-registry:
    image: confluentinc/cp-schema-registry:${SCHEMA_REGISTRY_VERSION}
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: http
    networks:
      - app-tier

  mysql:
    image: mysql:${MYSQL_VERSION}
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: mauFJcuf5dhRMQrjj
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-tier

  #ksqldb:
  #  image: confluentinc/cp-ksql-server:${KSQL_VERSION}
  #  hostname: ksqldb
  #  container_name: ksqldb
  #  ports:
  #    - 8088:8088
  #  networks:
  #    - app-tier
  #  depends_on:
  #    - kafka
  #    - schema-registry
  #  volumes:
  #    - ksqldb_data:/opt/ksqldb-udfs
  #  environment:
  #    KSQL_LISTENERS: http://0.0.0.0:8088
  #    KSQL_BOOTSTRAP_SERVERS: kafka:9092
  #    KSQL_KSQL_SCHEMA_REGISTRY_URL: http://schema-registry:8081
  #    KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: true
  #    KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: true
  #    KSQL_KSQL_EXTENSION_DIR: /opt/ksqldb-udfs
  
  #ksql-cli:
  #  image: confluentinc/cp-ksql-cli:${KSQL_CLI_VERSION}
  #  container_name: ksql-cli
  #  networks:
  #    - app-tier
  #  depends_on:
  #    - ksqldb
  #  volumes:
  #    - ksql_cli_data:/data/scripts/
  #  entrypoint: /bin/sh
  #  tty: true

  prometheus:
    image: bitnami/prometheus:${PROMETHEUS_VERSION}
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prom_exporter/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    networks:
      - app-tier
    depends_on:
      - kafka

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - app-tier
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION}
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_kafka_data:/data
    ports:
      - 9000:9000
    networks:
      - app-tier

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  kafka_ui_data:
    driver: local
  postgres_data:
    driver: local
  mysql_data:
    driver: local
  grafana_data:
    driver: local
  portainer_kafka_data:
    driver: local
  #ksqldb_data:
    #driver: local
  #ksql_cli_data:
    #driver: local 